SET IDENTITY_INSERT [dbo].[TB_Microregiao] ON

INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (1, 'Porto Velho', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (2, 'Guajará-Mirim', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (3, 'Ariquemes', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (4, 'Ji-Paraná', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (5, 'Alvorada D''Oeste', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (6, 'Cacoal', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (7, 'Vilhena', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (8, 'Colorado do Oeste', 'RO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (9, 'Cruzeiro do Sul', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (10, 'Tarauacá', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (11, 'Sena Madureira', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (12, 'Rio Branco', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (13, 'Brasiléia', 'AC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (14, 'Rio Negro', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (15, 'Japurá', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (16, 'Alto Solimões', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (17, 'Juruá', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (18, 'Tefé', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (19, 'Coari', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (20, 'Manaus', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (21, 'Rio Preto da Eva', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (22, 'Itacoatiara', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (23, 'Parintins', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (24, 'Boca do Acre', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (25, 'Purus', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (26, 'Madeira', 'AM')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (27, 'Boa Vista', 'RR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (28, 'Nordeste de Roraima', 'RR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (29, 'Caracaraí', 'RR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (30, 'Sudeste de Roraima', 'RR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (31, 'Óbidos', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (32, 'Santarém', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (33, 'Almeirim', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (34, 'Portel', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (35, 'Furos de Breves', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (36, 'Arari', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (37, 'Belém', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (38, 'Castanhal', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (39, 'Salgado', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (40, 'Bragantina', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (41, 'Cametá', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (42, 'Tomé-Açu', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (43, 'Guamá', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (44, 'Itaituba', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (45, 'Altamira', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (46, 'Tucuruí', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (47, 'Paragominas', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (48, 'São Félix do Xingu', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (49, 'Parauapebas', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (50, 'Marabá', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (51, 'Redenção', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (52, 'Conceição do Araguaia', 'PA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (53, 'Oiapoque', 'AP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (54, 'Amapá', 'AP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (55, 'Macapá', 'AP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (56, 'Mazagão', 'AP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (57, 'Bico do Papagaio', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (58, 'Araguaína', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (59, 'Miracema do Tocantins', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (60, 'Rio Formoso', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (61, 'Gurupi', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (62, 'Porto Nacional', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (63, 'Jalapão', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (64, 'Dianópolis', 'TO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (65, 'Litoral Ocidental Maranhense', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (66, 'Aglomeração Urbana de São Luís', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (67, 'Rosário', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (68, 'Lençois Maranhenses', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (69, 'Baixada Maranhense', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (70, 'Itapecuru Mirim', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (71, 'Gurupi', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (72, 'Pindaré', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (73, 'Imperatriz', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (74, 'Médio Mearim', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (75, 'Alto Mearim e Grajaú', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (76, 'Presidente Dutra', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (77, 'Baixo Parnaíba Maranhense', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (78, 'Chapadinha', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (79, 'Codó', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (80, 'Coelho Neto', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (81, 'Caxias', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (82, 'Chapadas do Alto Itapecuru', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (83, 'Porto Franco', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (84, 'Gerais de Balsas', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (85, 'Chapadas das Mangabeiras', 'MA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (86, 'Baixo Parnaíba Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (87, 'Litoral Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (88, 'Teresina', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (89, 'Campo Maior', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (90, 'Médio Parnaíba Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (91, 'Valença do Piauí', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (92, 'Alto Parnaíba Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (93, 'Bertolínia', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (94, 'Floriano', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (95, 'Alto Médio Gurguéia', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (96, 'São Raimundo Nonato', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (97, 'Chapadas do Extremo Sul Piauiense', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (98, 'Picos', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (99, 'Pio IX', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (100, 'Alto Médio Canindé', 'PI')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (101, 'Litoral de Camocim e Acaraú', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (102, 'Ibiapaba', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (103, 'Coreaú', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (104, 'Meruoca', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (105, 'Sobral', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (106, 'Ipu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (107, 'Santa Quitéria', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (108, 'Itapipoca', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (109, 'Baixo Curu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (110, 'Uruburetama', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (111, 'Médio Curu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (112, 'Canindé', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (113, 'Baturité', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (114, 'Chorozinho', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (115, 'Cascavel', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (116, 'Fortaleza', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (117, 'Pacajus', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (118, 'Sertão de Cratéus', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (119, 'Sertão de Quixeramobim', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (120, 'Sertão de Inhamuns', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (121, 'Sertão de Senador Pompeu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (122, 'Litoral de Aracati', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (123, 'Baixo Jaguaribe', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (124, 'Médio Jaguaribe', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (125, 'Serra do Pereiro', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (126, 'Iguatu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (127, 'Várzea Alegre', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (128, 'Lavras da Mangabeira', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (129, 'Chapada do Araripe', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (130, 'Caririaçu', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (131, 'Barro', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (132, 'Cariri', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (133, 'Brejo Santo', 'CE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (134, 'Mossoró', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (135, 'Chapada do Apodi', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (136, 'Médio Oeste', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (137, 'Vale do Açu', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (138, 'Serra de São Miguel', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (139, 'Pau dos Ferros', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (140, 'Umarizal', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (141, 'Macau', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (142, 'Angicos', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (143, 'Serra de Santana', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (144, 'Seridó Ocidental', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (145, 'Seridó Oriental', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (146, 'Baixa Verde', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (147, 'Borborema Potiguar', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (148, 'Agreste Potiguar', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (149, 'Litoral Nordeste', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (150, 'Macaíba', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (151, 'Natal', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (152, 'Litoral Sul', 'RN')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (153, 'Catolé do Rocha', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (154, 'Cajazeiras', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (155, 'Sousa', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (156, 'Patos', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (157, 'Piancó', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (158, 'Itaporanga', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (159, 'Serra do Teixeira', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (160, 'Seridó Ocidental Paraibano', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (161, 'Seridó Oriental Paraibano', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (162, 'Cariri Ocidental', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (163, 'Cariri Oriental', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (164, 'Curimataú Ocidental', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (165, 'Curimataú Oriental', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (166, 'Esperança', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (167, 'Brejo Paraibano', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (168, 'Guarabira', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (169, 'Campina Grande', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (170, 'Itabaiana', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (171, 'Umbuzeiro', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (172, 'Litoral Norte', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (173, 'Sapé', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (174, 'João Pessoa', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (175, 'Litoral Sul', 'PB')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (176, 'Araripina', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (177, 'Salgueiro', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (178, 'Pajeú', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (179, 'Sertão do Moxotó', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (180, 'Petrolina', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (181, 'Itaparica', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (182, 'Vale do Ipanema', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (183, 'Vale do Ipojuca', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (184, 'Alto Capibaribe', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (185, 'Médio Capibaribe', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (186, 'Garanhuns', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (187, 'Brejo Pernambucano', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (188, 'Mata Setentrional Pernambucana', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (189, 'Vitória de Santo Antão', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (190, 'Mata Meridional Pernambucana', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (191, 'Itamaracá', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (192, 'Recife', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (193, 'Suape', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (194, 'Fernando de Noronha', 'PE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (195, 'Serrana do Sertão Alagoano', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (196, 'Alagoana do Sertão do São Francisco', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (197, 'Santana do Ipanema', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (198, 'Batalha', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (199, 'Palmeira dos Índios', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (200, 'Arapiraca', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (201, 'Traipu', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (202, 'Serrana dos Quilombos', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (203, 'Mata Alagoana', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (204, 'Litoral Norte Alagoano', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (205, 'Maceió', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (206, 'São Miguel dos Campos', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (207, 'Penedo', 'AL')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (208, 'Sergipana do Sertão do São Francisco', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (209, 'Carira', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (210, 'Nossa Senhora das Dores', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (211, 'Agreste de Itabaiana', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (212, 'Tobias Barreto', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (213, 'Agreste de Lagarto', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (214, 'Propriá', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (215, 'Cotinguiba', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (216, 'Japaratuba', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (217, 'Baixo Cotinguiba', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (218, 'Aracaju', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (219, 'Boquim', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (220, 'Estância', 'SE')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (221, 'Barreiras', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (222, 'Cotegipe', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (223, 'Santa Maria da Vitória', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (224, 'Juazeiro', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (225, 'Paulo Afonso', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (226, 'Barra', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (227, 'Bom Jesus da Lapa', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (228, 'Senhor do Bonfim', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (229, 'Irecê', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (230, 'Jacobina', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (231, 'Itaberaba', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (232, 'Feira de Santana', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (233, 'Jeremoabo', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (234, 'Euclides da Cunha', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (235, 'Ribeira do Pombal', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (236, 'Serrinha', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (237, 'Alagoinhas', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (238, 'Entre Rios', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (239, 'Catu', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (240, 'Santo Antônio de Jesus', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (241, 'Salvador', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (242, 'Boquira', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (243, 'Seabra', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (244, 'Jequié', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (245, 'Livramento do Brumado', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (246, 'Guanambi', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (247, 'Brumado', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (248, 'Vitória da Conquista', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (249, 'Itapetinga', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (250, 'Valença', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (251, 'Ilhéus-Itabuna', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (252, 'Porto Seguro', 'BA')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (253, 'Unaí', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (254, 'Paracatu', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (255, 'Januária', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (256, 'Janaúba', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (257, 'Salinas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (258, 'Pirapora', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (259, 'Montes Claros', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (260, 'Grão Mogol', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (261, 'Bocaiúva', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (262, 'Diamantina', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (263, 'Capelinha', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (264, 'Araçuaí', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (265, 'Pedra Azul', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (266, 'Almenara', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (267, 'Teófilo Otoni', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (268, 'Nanuque', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (269, 'Ituiutaba', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (270, 'Uberlândia', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (271, 'Patrocínio', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (272, 'Patos de Minas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (273, 'Frutal', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (274, 'Uberaba', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (275, 'Araxá', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (276, 'Três Marias', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (277, 'Curvelo', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (278, 'Bom Despacho', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (279, 'Sete Lagoas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (280, 'Conceição do Mato Dentro', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (281, 'Pará de Minas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (282, 'Belo Horizonte', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (283, 'Itabira', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (284, 'Itaguara', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (285, 'Ouro Preto', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (286, 'Conselheiro Lafaiete', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (287, 'Guanhães', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (288, 'Peçanha', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (289, 'Governador Valadares', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (290, 'Mantena', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (291, 'Ipatinga', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (292, 'Caratinga', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (293, 'Aimorés', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (294, 'PiŒí', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (295, 'Divinópolis', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (296, 'Formiga', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (297, 'Campo Belo', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (298, 'Oliveira', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (299, 'Passos', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (300, 'São Sebastião do Paraíso', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (301, 'Alfenas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (302, 'Varginha', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (303, 'Poços de Caldas', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (304, 'Pouso Alegre', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (305, 'Santa Rita do Sapucaí', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (306, 'São Lourenço', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (307, 'Andrelândia', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (308, 'Itajubá', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (309, 'Lavras', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (310, 'São João Del Rei', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (311, 'Barbacena', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (312, 'Ponte Nova', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (313, 'Manhuaçu', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (314, 'Viçosa', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (315, 'Muriaé', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (316, 'Ubá', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (317, 'Juiz de Fora', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (318, 'Cataguases', 'MG')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (319, 'Barra de São Francisco', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (320, 'Nova Venécia', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (321, 'Colatina', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (322, 'Montanha', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (323, 'São Mateus', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (324, 'Linhares', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (325, 'Afonso Cláudio', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (326, 'Santa Teresa', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (327, 'Vitória', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (328, 'Guarapari', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (329, 'Alegre', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (330, 'Cachoeiro de Itapemirim', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (331, 'Itapemirim', 'ES')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (332, 'Itaperuna', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (333, 'Santo Antônio de Pádua', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (334, 'Campos dos Goytacazes', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (335, 'Macaé', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (336, 'Três Rios', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (337, 'Cantagalo-Cordeiro', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (338, 'Nova Friburgo', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (339, 'Santa Maria Madalena', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (340, 'Bacia de São João', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (341, 'Lagos', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (342, 'Vale do Paraíba Fluminense', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (343, 'Barra do Piraí', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (344, 'Baía da Ilha Grande', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (345, 'Vassouras', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (346, 'Serrana', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (347, 'Macacu-Caceribu', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (348, 'Itaguaí', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (349, 'Rio de Janeiro', 'RJ')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (350, 'Jales', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (351, 'Fernandópolis', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (352, 'Votuporanga', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (353, 'São José do Rio Preto', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (354, 'Catanduva', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (355, 'Auriflama', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (356, 'Nhandeara', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (357, 'Novo Horizonte', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (358, 'Barretos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (359, 'São Joaquim da Barra', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (360, 'Ituverava', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (361, 'Franca', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (362, 'Jaboticabal', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (363, 'Ribeirão Preto', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (364, 'Batatais', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (365, 'Andradina', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (366, 'Araçatuba', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (367, 'Birigui', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (368, 'Lins', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (369, 'Bauru', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (370, 'Jaú', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (371, 'Avaré', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (372, 'Botucatu', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (373, 'Araraquara', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (374, 'São Carlos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (375, 'Rio Claro', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (376, 'Limeira', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (377, 'Piracicaba', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (378, 'Pirassununga', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (379, 'São João da Boa Vista', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (380, 'Moji-Mirim', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (381, 'Campinas', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (382, 'Amparo', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (383, 'Dracena', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (384, 'Adamantina', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (385, 'Presidente Prudente', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (386, 'Tupã', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (387, 'Marília', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (388, 'Assis', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (389, 'Ourinhos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (390, 'Itapeva', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (391, 'Itapetininga', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (392, 'Tatuí', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (393, 'Capão Bonito', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (394, 'Piedade', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (395, 'Sorocaba', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (396, 'Jundiaí', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (397, 'Bragança Paulista', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (398, 'Campos do Jordão', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (399, 'São José dos Campos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (400, 'Guaratinguetá', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (401, 'Bananal', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (402, 'Paraibuna/Paraitinga', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (403, 'Caraguatatuba', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (404, 'Registro', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (405, 'Itanhaém', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (406, 'Osasco', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (407, 'Franco da Rocha', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (408, 'Guarulhos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (409, 'Itapecerica da Serra', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (410, 'São Paulo', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (411, 'Moji das Cruzes', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (412, 'Santos', 'SP')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (413, 'Paranavaí', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (414, 'Umuarama', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (415, 'Cianorte', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (416, 'Goioerê', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (417, 'Campo Mourão', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (418, 'Astorga', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (419, 'Porecatú', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (420, 'Floraí', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (421, 'Maringá', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (422, 'Apucarana', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (423, 'Londrina', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (424, 'Faxinal', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (425, 'Ivaiporã', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (426, 'Assaí', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (427, 'Cornélio Procópio', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (428, 'Jacarezinho', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (429, 'Ibaití', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (430, 'Wesceslau Braz', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (431, 'Telêmaco Borba', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (432, 'Jaguariaíva', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (433, 'Ponta Grossa', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (434, 'Toledo', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (435, 'Cascavel', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (436, 'Foz do Iguaçu', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (437, 'Capanema', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (438, 'Francisco Beltrão', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (439, 'Pato Branco', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (440, 'Pitanga', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (441, 'Guarapuava', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (442, 'Palmas', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (443, 'Prudentópolis', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (444, 'Irati', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (445, 'União da Vitória', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (446, 'São Mateus do Sul', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (447, 'Cerro Azul', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (448, 'Lapa', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (449, 'Curitiba', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (450, 'Paranaguá', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (451, 'Rio Negro', 'PR')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (452, 'São Miguel d''Oeste', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (453, 'Chapecó', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (454, 'Xanxerê', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (455, 'Joaçaba', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (456, 'Concórdia', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (457, 'Canoinhas', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (458, 'São Bento do Sul', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (459, 'Joinville', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (460, 'Curitibanos', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (461, 'Campos de Lages', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (462, 'Rio do Sul', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (463, 'Blumenau', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (464, 'Itajaí', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (465, 'Ituporanga', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (466, 'Tijucas', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (467, 'Florianópolis', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (468, 'Tabuleiro', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (469, 'Tubarão', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (470, 'Criciúma', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (471, 'Araranguá', 'SC')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (472, 'Santa Rosa', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (473, 'Três Passos', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (474, 'Frederico Westphalen', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (475, 'Erechim', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (476, 'Sananduva', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (477, 'Cerro Largo', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (478, 'Santo Ângelo', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (479, 'Ijuí', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (480, 'Carazinho', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (481, 'Passo Fundo', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (482, 'Cruz Alta', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (483, 'Não-Me-Toque', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (484, 'Soledade', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (485, 'Guaporé', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (486, 'Vacaria', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (487, 'Caxias do Sul', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (488, 'Santiago', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (489, 'Santa Maria', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (490, 'Restinga Seca', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (491, 'Santa Cruz do Sul', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (492, 'Lajeado-Estrela', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (493, 'Cachoeira do Sul', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (494, 'Montenegro', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (495, 'Gramado-Canela', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (496, 'São Jerônimo', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (497, 'Porto Alegre', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (498, 'Osório', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (499, 'Camaquã', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (500, 'Campanha Ocidental', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (501, 'Campanha Central', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (502, 'Campanha Meridional', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (503, 'Serras de Sudeste', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (504, 'Pelotas', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (505, 'Jaguarão', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (506, 'Litoral Lagunar', 'RS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (507, 'Baixo Pantanal', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (508, 'Aquidauana', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (509, 'Alto Taquari', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (510, 'Campo Grande', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (511, 'Cassilândia', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (512, 'Paranaíba', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (513, 'Três Lagoas', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (514, 'Nova Andradina', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (515, 'Bodoquena', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (516, 'Dourados', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (517, 'Iguatemi', 'MS')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (518, 'Aripuanã', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (519, 'Alta Floresta', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (520, 'Colíder', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (521, 'Parecis', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (522, 'Arinos', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (523, 'Alto Teles Pires', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (524, 'Sinop', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (525, 'Paranatinga', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (526, 'Norte Araguaia', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (527, 'Canarana', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (528, 'Médio Araguaia', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (529, 'Alto Guaporé', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (530, 'Tangará da Serra', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (531, 'Jauru', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (532, 'Alto Paraguai', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (533, 'Rosário Oeste', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (534, 'Cuiabá', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (535, 'Alto Pantanal', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (536, 'Primavera do Leste', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (537, 'Tesouro', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (538, 'Rondonópolis', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (539, 'Alto Araguaia', 'MT')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (540, 'São Miguel do Araguaia', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (541, 'Rio Vermelho', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (542, 'Aragarças', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (543, 'Porangatu', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (544, 'Chapada dos Veadeiros', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (545, 'Ceres', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (546, 'Anápolis', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (547, 'Iporá', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (548, 'Anicuns', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (549, 'Goiânia', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (550, 'Vão do Paranã', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (551, 'Entorno de Brasília', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (552, 'Sudoeste de Goiás', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (553, 'Vale do Rio dos Bois', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (554, 'Meia Ponte', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (555, 'Pires do Rio', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (556, 'Catalão', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (557, 'Quirinópolis', 'GO')
INSERT INTO [dbo].[TB_Microregiao] ([ID], [DESCR], [SiglaUF]) VALUES (558, 'Brasília', 'DF')

SET IDENTITY_INSERT [dbo].[TB_Microregiao] OFF
