
SET IDENTITY_INSERT [dbo].[TB_Bancos] ON

INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (1, 246, 'Banco ABC Brasil S.A. ', 'http://www.abcbrasil.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (2, 356, 'Banco ABN AMRO Real S.A. ', 'http://www.abnamro.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (3, 25, 'Banco Alfa S.A. ', 'http://www.bancoalfa.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (4, 641, 'Banco Alvorada S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (5, NULL, 'Banco American Express S.A. ', 'http://www.aexp.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (6, 29, 'Banco Banerj S.A. ', 'http://www.banerj.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (7, 38, 'Banco Banestado S.A. ', 'http://www.banestado.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (8, 740, 'Banco Barclays S.A. ', 'http://www.barclays.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (9, 107, 'Banco BBM S.A. ', 'http://www.bbmbank.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (10, 31, 'Banco Beg S.A. ', 'http://www.itau.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (11, 36, 'Banco Bem S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (12, 394, 'Banco BMC S.A. ', 'http://www.bmc.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (13, 318, 'Banco BMG S.A. ', 'http://www.bancobmg.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (14, 752, 'Banco BNP Paribas Brasil S.A. ', 'http://www.bnpparibas.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (15, 248, 'Banco Boavista Interatlântico S.A. ', 'não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (16, 237, 'Banco Bradesco S.A. ', 'http://www.bradesco.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (17, 225, 'Banco Brascan S.A. ', 'http://www.bancobrascan.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (18, 263, 'Banco Cacique S.A. ', 'http://www.bancocacique.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (19, 222, 'Banco Calyon Brasil S.A. ', 'http://www.calyon.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (20, 40, 'Banco Cargill S.A. ', 'http://www.bancocargill.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (21, 745, 'Banco Citibank S.A. ', 'http://www.citibank.com/brasil ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (22, 215, 'Banco Comercial e de Investimento Sudameris S.A. ', 'Não possui site')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (23, 756, 'Banco Cooperativo do Brasil S.A. - BANCOOB ', 'http://www.bancoob.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (24, 748, 'Banco Cooperativo Sicredi S.A. - BANSICREDI ', 'http://www.bansicredi.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (25, 505, 'Banco Credit Suisse (Brasil) S.A. ', 'http://www.csfb.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (26, 229, 'Banco Cruzeiro do Sul S.A. ', 'http://www.bcsul.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (27, 3, 'Banco da Amazônia S.A. ', 'http://www.bancoamazonia.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (28, 707, 'Banco Daycoval S.A. ', 'http://www.daycoval.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (29, NULL, 'Banco de Lage Landen Brasil S.A. ', 'http://www.delagelanden.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (30, 24, 'Banco de Pernambuco S.A. - BANDEPE ', 'http://www.bandepe.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (31, 456, 'Banco de Tokyo-Mitsubishi Brasil S.A. ', 'http://www.btm.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (32, 214, 'Banco Dibens S.A. ', 'http://www.bancodibens.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (33, 1, 'Banco do Brasil S.A. ', 'http://www.bb.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (34, 27, 'Banco do Estado de Santa Catarina S.A. ', 'http://www.besc.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (35, 33, 'Banco do Estado de São Paulo S.A. - Banespa ', 'http://www.banespa.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (36, 47, 'Banco do Estado de Sergipe S.A. ', 'http://www.banese.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (37, 37, 'Banco do Estado do Pará S.A. ', 'http://www.banparanet.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (38, 41, 'Banco do Estado do Rio Grande do Sul S.A. ', 'http://www.banrisul.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (39, 4, 'Banco do Nordeste do Brasil S.A. ', 'http://www.banconordeste.gov.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (40, 265, 'Banco Fator S.A. ', 'http://www.bancofator.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (41, NULL, 'Banco Fiat S.A. ', 'http://www.bancofiat.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (42, 224, 'Banco Fibra S.A. ', 'http://www.bancofibra.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (43, 175, 'Banco Finasa S.A. ', 'não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (44, 252, 'Banco Fininvest S.A. ', 'http://www.fininvest.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (45, 233, 'Banco GE Capital S.A. ', 'http://www.bancoge.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (46, NULL, 'Banco General Motors S.A. ', 'http://www.bancogm.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (47, 734, 'Banco Gerdau S.A. ', 'http://www.bancogerdau.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (48, 612, 'Banco Guanabara S.A. ', 'não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (49, 63, 'Banco Ibi S.A. Banco Múltiplo ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (50, 604, 'Banco Industrial do Brasil S.A. ', 'http://www.bancoindustrial.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (51, 320, 'Banco Industrial e Comercial S.A. ', 'http://www.bicbanco.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (52, 653, 'Banco Indusval S.A. ', 'http://www.indusval.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (53, 630, 'Banco Intercap S.A. ', 'http://www.intercap.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (54, 249, 'Banco Investcred Unibanco S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (55, 48, 'Banco Itaú BBA S.A. ', 'http://www.itaubba.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (56, 652, 'Banco Itaú Holding Financeira S.A. ', 'http://www.itau.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (57, 341, 'Banco Itaú S.A. ', 'http://www.itau.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (58, NULL, 'Banco Itaucred Financiamentos S.A. ', 'http://www.itaucred.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (59, NULL, 'Banco Itausaga S.A. ', 'http://www.itau.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (60, 376, 'Banco J. P. Morgan S.A. ', 'http://www.jpmorgan.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (61, 74, 'Banco J. Safra S.A. ', 'http://www.jsafra.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (62, 757, 'Banco KEB do Brasil S.A. ', 'não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (63, 600, 'Banco Luso Brasileiro S.A. ', 'http://www.lusobrasileiro.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (64, 392, 'Banco Mercantil de São Paulo S.A. ', 'não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (65, 389, 'Banco Mercantil do Brasil S.A. ', 'http://www.mercantil.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (66, 755, 'Banco Merrill Lynch de Investimentos S.A. ', 'http://www.ml.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (67, 151, 'Banco Nossa Caixa S.A. ', 'http://www.nossacaixa.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (68, 45, 'Banco Opportunity S.A. ', 'http://www.opportunity.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (69, 208, 'Banco Pactual S.A. ', 'http://www.pactual.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (70, 623, 'Banco Panamericano S.A. ', 'http://www.panamericano.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (71, 611, 'Banco Paulista S.A. ', 'http://www.bancopaulista.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (72, 643, 'Banco Pine S.A. ', 'http://www.bancopine.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (73, 638, 'Banco Prosper S.A. ', 'http://www.bancoprosper.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (74, 747, 'Banco Rabobank International Brasil S.A. ', 'http://www.rabobank.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (75, 633, 'Banco Rendimento S.A. ', 'http://www.rendimento.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (76, 72, 'Banco Rural Mais S.A. ', 'http://www.rural.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (77, 453, 'Banco Rural S.A. ', 'http://www.rural.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (78, 422, 'Banco Safra S.A. ', 'http://www.safra.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (79, 353, 'Banco Santander Brasil S.A. ', 'http://www.santander.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (80, 8, 'Banco Santander Meridional S.A. ', 'http://www.meridional.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (81, 351, 'Banco Santander S.A. ', 'http://www.santander.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (82, 250, 'Banco Schahin S.A. ', 'http://www.bancoschahin.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (83, 749, 'Banco Simples S.A. ', 'http://www.bancosimples.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (84, 366, 'Banco Société Générale Brasil S.A. ', 'http://www.sgbrasil.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (85, 637, 'Banco Sofisa S.A. ', 'http://www.sofisa.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (86, 347, 'Banco Sudameris Brasil S.A. ', 'http://www.sudameris.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (87, 464, 'Banco Sumitomo Mitsui Brasileiro S.A. ', 'http://não%20possue%20site/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (88, 634, 'Banco Triângulo S.A. ', 'http://www.tribanco.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (89, 247, 'Banco UBS S.A. ', 'http://www.ubsw.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (90, 116, 'Banco Único S.A. ', 'http://www.unibanco.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (91, 655, 'Banco Votorantim S.A. ', 'http://www.bancovotorantim.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (92, 610, 'Banco VR S.A. ', 'http://www.vr.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (93, 370, 'Banco WestLB do Brasil S.A. ', 'http://www.westlb.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (94, 21, 'BANESTES S.A. Banco do Estado do Espírito Santo ', 'http://www.banestes.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (95, 719, 'Banif-Banco Internacional do Funchal (Brasil)S.A. ', 'http://www.banif.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (96, 479, 'BankBoston Banco Múltiplo S.A. ', 'http://www.bankboston.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (97, 744, 'BankBoston N.A. ', 'http://www.bankboston.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (98, NULL, 'BB Banco Popular do Brasil S.A. ', 'http://www.bancopopulardobrasil.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (99, NULL, 'BES Investimento do Brasil S.A.-Banco de Investimento ', 'http://www.besinvestimento.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (100, 70, 'BRB - Banco de Brasília S.A. ', 'http://www.brb.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (101, 104, 'Caixa Econômica Federal ', 'http://www.caixa.gov.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (102, 477, 'Citibank N.A. ', 'http://www.citibank.com/brasil ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (103, NULL, 'Credicard Banco S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (104, 487, 'Deutsche Bank S.A. - Banco Alemão ', 'http://www.deutsche-bank.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (105, 751, 'Dresdner Bank Brasil S.A. - Banco Múltiplo ', 'http://www.drkw.net/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (106, 210, 'Dresdner Bank Lateinamerika Aktiengesellschaft ', 'http://www.dbla.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (107, 62, 'Hipercard Banco Múltiplo S.A. ', 'http://www.banco1.net/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (108, 399, 'HSBC Bank Brasil S.A. - Banco Múltiplo ', 'http://www.hsbc.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (109, 492, 'ING Bank N.V. ', 'http://www.ing.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (110, 488, 'JPMorgan Chase Bank ', 'http://www.jpmorganchase.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (111, 65, 'Lemon Bank Banco Múltiplo S.A. ', 'http://www.lemon.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (112, 409, 'UNIBANCO - União de Bancos Brasileiros S.A. ', 'http://www.unibanco.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (113, 230, 'Unicard Banco Múltiplo S.A. ', 'http://www.unicard.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (117, 654, 'Banco A.J.Renner S.A. ', 'http://www.bancorenner.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (118, 213, 'Banco Arbi S.A. ', 'http://www.arbi.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (119, 739, 'Banco BGN S.A. ', 'http://www.bgn.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (120, 96, 'Banco BM&F de Serviços de Liquidação e Custódia S.A ', 'http://www.bmf.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (121, 218, 'Banco Bonsucesso S.A. ', 'http://www.bancobonsucesso.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (122, NULL, 'Banco BRJ S.A. ', 'http://www.brjbank.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (123, 44, 'Banco BVA S.A. ', 'http://www.bancobva.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (124, 412, 'Banco Capital S.A. ', 'http://www.bancocapital.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (125, 266, 'Banco Cédula S.A. ', 'http://www.bancocedula.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (126, 241, 'Banco Clássico S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (127, NULL, 'Banco CNH Capital S.A. ', 'http://www.bancocnh.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (128, 753, 'Banco Comercial Uruguai S.A. ', 'http://www.bancocomercial.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (129, 75, 'Banco CR2 S.A. ', 'Não possui site')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (130, 721, 'Banco Credibel S.A. ', 'http://www.credibel.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (131, NULL, 'Banco Daimlerchrysler S.A. ', 'http://www.bancodaimlerchrysler.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (132, 300, 'Banco de La Nacion Argentina ', 'http://www.bna.com.ar/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (133, 495, 'Banco de La Provincia de Buenos Aires ', 'http://www.bapro.com.ar/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (134, 494, 'Banco de La Republica Oriental del Uruguay ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (135, 35, 'Banco do Estado do Ceará S.A. - BEC ', 'http://www.bec.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (136, 39, 'Banco do Estado do Piauí S.A. - BEP ', 'http://www.bep.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (137, 743, 'Banco Emblema S.A. ', 'http://www.bancoemblema.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (138, 626, 'Banco Ficsa S.A. ', 'http://www.ficsa.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (139, NULL, 'Banco Ford S.A. ', 'http://www.bancoford.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (140, NULL, 'Banco Honda S.A. ', 'http://www.bancohonda.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (141, NULL, 'Banco IBM S.A. ', 'http://www.ibm.com/br/financing/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (142, 217, 'Banco John Deere S.A. ', 'http://www.johndeere.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (143, 212, 'Banco Matone S.A. ', 'http://www.bancomatone.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (144, 243, 'Banco Máxima S.A. ', 'http://www.bancomaxima.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (145, NULL, 'Banco Maxinvest S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (146, 746, 'Banco Modal S.A. ', 'http://www.bancomodal.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (147, NULL, 'Banco Moneo S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (148, 738, 'Banco Morada S.A. ', 'http://www.bancomorada.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (149, 66, 'Banco Morgan Stanley Dean Witter S.A. ', 'http://www.morganstanley.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (150, NULL, 'Banco Ourinvest S.A. ', 'http://www.ourinvest.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (151, 613, 'Banco Pecúnia S.A. ', 'http://www.bancopecunia.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (152, 724, 'Banco Porto Seguro S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (153, 735, 'Banco Pottencial S.A. ', 'http://www.pottencial.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (154, NULL, 'Banco PSA Finance Brasil S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (155, 741, 'Banco Ribeirão Preto S.A. ', 'http://www.brp.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (156, NULL, 'Banco Rodobens S.A. ', 'http://www.rodobens.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (157, NULL, 'Banco Toyota do Brasil S.A. ', 'http://www.bancotoyota.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (158, NULL, 'Banco Tricury S.A. ', 'http://www.tricury.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (159, NULL, 'Banco Volkswagen S.A. ', 'http://www.bancovw.com.br/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (160, NULL, 'Banco Volvo (Brasil) S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (161, NULL, 'BPN Brasil Banco Mútiplo S.A. ', 'Não possui site ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (162, 64, 'Goldman Sachs do Brasil Banco Múltiplo S.A. ', 'http://www.goldmansachs.com/ ')
INSERT INTO [dbo].[TB_Bancos] ([ID], [COD_BANCO], [DESCR], [SITE]) VALUES (163, 254, 'Paraná Banco S.A. ', 'http://www.paranabanco.com.br/ ')

SET IDENTITY_INSERT [dbo].[TB_Bancos] OFF
