SET IDENTITY_INSERT [dbo].[TB_TipoLogradouro] ON

INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (1, 'Avenida          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (2, 'Aeroporto        ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (3, 'Alameda          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (4, 'Área             ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (5, 'Campo            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (6, 'Chácara          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (7, 'Colônia          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (8, 'Condomínio       ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (9, 'Conjunto         ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (10, 'Distrito         ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (11, 'Esplanada        ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (12, 'Estação          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (13, 'Estrada          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (14, 'Favela           ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (15, 'Fazenda          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (16, 'Feira            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (17, 'Jardim           ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (18, 'Ladeira          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (19, 'Lago             ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (20, 'Lagoa            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (21, 'Largo            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (22, 'Loteamento       ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (23, 'Morro            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (24, 'Núcleo           ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (25, 'Parque           ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (26, 'Passarela        ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (27, 'Pátio            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (28, 'Praça            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (29, 'Quadra           ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (30, 'Recanto          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (31, 'Residencial      ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (32, 'Rodovia          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (33, 'Setor            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (34, 'Sítio            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (35, 'Travessa         ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (36, 'Trecho           ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (37, 'Trevo            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (38, 'Vale             ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (39, 'Vereda           ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (40, 'Via              ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (41, 'Viaduto          ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (42, 'Viela            ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (43, 'Vila             ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (44, 'Outros           ')
INSERT INTO [dbo].[TB_TipoLogradouro] ([ID], [TipoLogradouro]) VALUES (45, 'Rua')

SET IDENTITY_INSERT [dbo].[TB_TipoLogradouro] OFF
