SET IDENTITY_INSERT [dbo].[TB_Mesoregiao] ON

INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (1, 'Madeira-Guaporé', 'RO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (2, 'Leste Rondoniense', 'RO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (3, 'Vale do Juruá', 'AC')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (4, 'Vale do Acre', 'AC')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (5, 'Norte Amazonense', 'AM')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (6, 'Sudoeste Amazonense', 'AM')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (7, 'Centro Amazonense', 'AM')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (8, 'Sul Amazonense', 'AM')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (9, 'Norte de Roraima', 'RR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (10, 'Sul de Roraima', 'RR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (11, 'Baixo Amazonas', 'PA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (12, 'Marajó', 'PA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (13, 'Metropolitana de Belém', 'PA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (14, 'Nordeste Paraense', 'PA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (15, 'Sudoeste Paraense', 'PA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (16, 'Sudeste Paraense', 'PA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (17, 'Norte do Amapá', 'AP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (18, 'Sul do Amapá', 'AP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (19, 'Ocidental do Tocantins', 'TO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (20, 'Oriental do Tocantins', 'TO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (21, 'Norte Maranhense', 'MA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (22, 'Oeste Maranhense', 'MA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (23, 'Centro Maranhense', 'MA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (24, 'Leste Maranhense', 'MA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (25, 'Sul Maranhense', 'MA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (26, 'Norte Piauiense', 'PI')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (27, 'Centro-Norte Piauiense', 'PI')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (28, 'Sudoeste Piauiense', 'PI')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (29, 'Sudeste Piauiense', 'PI')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (30, 'Noroeste Cearense', 'CE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (31, 'Norte Cearense', 'CE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (32, 'Metropolitana de Fortaleza', 'CE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (33, 'Sertões Cearenses', 'CE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (34, 'Jaguaribe', 'CE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (35, 'Centro-Sul Cearense', 'CE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (36, 'Sul Cearense', 'CE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (37, 'Oeste Potiguar', 'RN')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (38, 'Central Potiguar', 'RN')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (39, 'Agreste Potiguar', 'RN')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (40, 'Leste Potiguar', 'RN')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (41, 'Sertão Paraibano', 'PB')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (42, 'Borborema', 'PB')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (43, 'Agreste Paraibano', 'PB')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (44, 'Mata Paraibana', 'PB')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (45, 'Sertão Pernambucano', 'PE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (46, 'São Francisco Pernambucano', 'PE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (47, 'Agreste Pernambucano', 'PE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (48, 'Mata Pernambucana', 'PE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (49, 'Metropolitana de Recife', 'PE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (50, 'Sertão Alagoano', 'AL')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (51, 'Agreste Alagoano', 'AL')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (52, 'Leste Alagoano', 'AL')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (53, 'Sertão Sergipano', 'SE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (54, 'Agreste Sergipano', 'SE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (55, 'Leste Sergipano', 'SE')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (56, 'Extremo Oeste Baiano', 'BA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (57, 'Vale São-Franciscano da Bahia', 'BA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (58, 'Centro Norte Baiano', 'BA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (59, 'Nordeste Baiano', 'BA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (60, 'Metropolitana de Salvador', 'BA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (61, 'Centro Sul Baiano', 'BA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (62, 'Sul Baiano', 'BA')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (63, 'Noroeste de Minas', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (64, 'Norte de Minas', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (65, 'Jequitinhonha', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (66, 'Vale do Mucuri', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (67, 'Triângulo Mineiro/Alto Paranaíba', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (68, 'Central Mineira', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (69, 'Metropolitana de Belo Horizonte', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (70, 'Vale do Rio Doce', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (71, 'Oeste de Minas', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (72, 'Sul/Sudoeste de Minas', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (73, 'Campo das Vertentes', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (74, 'Zona da Mata', 'MG')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (75, 'Noroeste Espírito-santense', 'ES')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (76, 'Litoral Norte Espírito-santense', 'ES')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (77, 'Central Espírito-santense', 'ES')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (78, 'Sul Espírito-santense', 'ES')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (79, 'Noroeste Fluminense', 'RJ')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (80, 'Norte Fluminense', 'RJ')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (81, 'Centro Fluminense', 'RJ')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (82, 'Baixadas', 'RJ')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (83, 'Sul Fluminense', 'RJ')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (84, 'Metropolitana do Rio de Janeiro', 'RJ')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (85, 'São José do Rio Preto', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (86, 'Ribeirão Preto', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (87, 'Araçatuba', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (88, 'Bauru', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (89, 'Araraquara', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (90, 'Piracicaba', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (91, 'Campinas', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (92, 'Presidente Prudente', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (93, 'Marília', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (94, 'Assis', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (95, 'Itapetininga', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (96, 'Macro Metropolitana Paulista', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (97, 'Vale do Paraíba Paulista', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (98, 'Litoral Sul Paulista', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (99, 'Metropolitana de São Paulo', 'SP')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (100, 'Noroeste Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (101, 'Centro Ocidental Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (102, 'Norte Central Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (103, 'Norte Pioneiro Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (104, 'Centro Oriental Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (105, 'Oeste Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (106, 'Sudoeste Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (107, 'Centro-Sul Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (108, 'Sudeste Paranaense', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (109, 'Metropolitana de Curitiba', 'PR')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (110, 'Oeste Catarinense', 'SC')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (111, 'Norte Catarinense', 'SC')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (112, 'Serrana', 'SC')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (113, 'Vale do Itajaí', 'SC')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (114, 'Grande Florianópolis', 'SC')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (115, 'Sul Catarinense', 'SC')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (116, 'Noroeste Rio-grandense', 'RS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (117, 'Nordeste Rio-grandense', 'RS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (118, 'Centro Ocidental Rio-grandense', 'RS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (119, 'Centro Oriental Rio-grandense', 'RS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (120, 'Metropolitana de Porto Alegre', 'RS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (121, 'Sudoeste Rio-grandense', 'RS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (122, 'Sudeste Rio-grandense', 'RS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (123, 'Pantanais Sul Mato-grossense', 'MS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (124, 'Centro Norte de Mato Grosso do Sul', 'MS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (125, 'Leste de Mato Grosso do Sul', 'MS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (126, 'Sudoeste de Mato Grosso do Sul', 'MS')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (127, 'Norte Mato-grossense', 'MT')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (128, 'Nordeste Mato-grossense', 'MT')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (129, 'Sudoeste Mato-grossense', 'MT')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (130, 'Centro-Sul Mato-grossense', 'MT')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (131, 'Sudeste Mato-grossense', 'MT')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (132, 'Noroeste Goiano', 'GO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (133, 'Norte Goiano', 'GO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (134, 'Centro Goiano', 'GO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (135, 'Leste Goiano', 'GO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (136, 'Sul Goiano', 'GO')
INSERT INTO [dbo].[TB_Mesoregiao] ([ID], [DESCR], [SiglaUF]) VALUES (137, 'Distrito Federal', 'DF')

SET IDENTITY_INSERT [dbo].[TB_Mesoregiao] OFF
