\i database.sql
\i funcoes.sql
\i td_emprestimo.sql
\i td_lancamento.sql
\i td_mensalidade.sql
\i td_quadroassociativo.sql
\i td_requisicao.sql
\i ti_emprestimo.sql
\i ti_lancamento.sql
\i ti_mensalidade.sql
--\i ti_mesreferencia.sql
\i ti_quadroassociativo.sql
\i ti_requisicao.sql
\i tu_associado.sql
\i tu_emprestimo.sql
\i tu_faixamensalidade.sql
\i tu_lancamento.sql
\i tu_mensalidade.sql
--\i tu_mesreferencia.sql
\i tu_quadroassociativo.sql
\i tu_requisicao.sql
